In [11]:
import pandas as pd 
df = pd.read_csv('twitter.csv')
df.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [12]:
import string 
string.punctuation

def remove_punctuation(text):
    return ''.join([i for i in text if i not in string.punctuation])

In [20]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [13]:
df['tweet_clean'] = df['tweet'].apply(lambda x: remove_punctuation(x))
df.head()

,id,label,tweet,tweet_clean
0,1,0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is so...
1,2,0,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...
2,3,0,bihday your majesty,bihday your majesty
3,4,0,#model i love u take with u all the time in ...,model i love u take with u all the time in u...
4,5,0,factsguide: society now #motivation,factsguide society now motivation

In [14]:
import re 
def tokenize(text):
    return text.split(' ')

df['tweet_tokenized'] = df['tweet_clean'].apply(lambda x: tokenize(x))
df.head()

,id,label,tweet,tweet_clean,tweet_tokenized
0,1,0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is so...,"[, user, when, a, father, is, dysfunctional, a..."
1,2,0,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...,"[user, user, thanks, for, lyft, credit, i, can..."
2,3,0,bihday your majesty,bihday your majesty,"[, , bihday, your, majesty]"
3,4,0,#model i love u take with u all the time in ...,model i love u take with u all the time in u...,"[model, , , i, love, u, take, with, u, all, th..."
4,5,0,factsguide: society now #motivation,factsguide society now motivation,"[, factsguide, society, now, , , , motivation]"

In [15]:
from nltk.stem.porter import PorterStemmer 

stemmer = PorterStemmer() 
def stemm(text):
    return [stemmer.stem(word) for word in text] 

df['tweet_stemmed'] = df['tweet_tokenized'].apply(lambda x: stemm(x))

In [16]:
df.head()

,id,label,tweet,tweet_clean,tweet_tokenized,tweet_stemmed
0,1,0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is so...,"[, user, when, a, father, is, dysfunctional, a...","[, user, when, a, father, is, dysfunct, and, i..."
1,2,0,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...,"[user, user, thanks, for, lyft, credit, i, can...","[user, user, thank, for, lyft, credit, i, cant..."
2,3,0,bihday your majesty,bihday your majesty,"[, , bihday, your, majesty]","[, , bihday, your, majesti]"
3,4,0,#model i love u take with u all the time in ...,model i love u take with u all the time in u...,"[model, , , i, love, u, take, with, u, all, th...","[model, , , i, love, u, take, with, u, all, th..."
4,5,0,factsguide: society now #motivation,factsguide society now motivation,"[, factsguide, society, now, , , , motivation]","[, factsguid, societi, now, , , , motiv]"

In [17]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download("wordnet")
nltk.download("omw-1.4")
# Initialize wordnet lemmatizer
wnl = WordNetLemmatizer()
def lemmatization(text):
    return [wnl.lemmatize(w, pos='v') for w in text]

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rs0238\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\rs0238\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [18]:
def lemmatization(text):
    return [wnl.lemmatize(w, pos='v') for w in text]

df['tweet_lemmatized'] = df['tweet_tokenized'].apply(lambda x: lemmatization(x))

In [19]:
df.head()

,id,label,tweet,tweet_clean,tweet_tokenized,tweet_stemmed,tweet_lemmatized
0,1,0,@user when a father is dysfunctional and is s...,user when a father is dysfunctional and is so...,"[, user, when, a, father, is, dysfunctional, a...","[, user, when, a, father, is, dysfunct, and, i...","[, user, when, a, father, be, dysfunctional, a..."
1,2,0,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit i cant use ca...,"[user, user, thanks, for, lyft, credit, i, can...","[user, user, thank, for, lyft, credit, i, cant...","[user, user, thank, for, lyft, credit, i, cant..."
2,3,0,bihday your majesty,bihday your majesty,"[, , bihday, your, majesty]","[, , bihday, your, majesti]","[, , bihday, your, majesty]"
3,4,0,#model i love u take with u all the time in ...,model i love u take with u all the time in u...,"[model, , , i, love, u, take, with, u, all, th...","[model, , , i, love, u, take, with, u, all, th...","[model, , , i, love, u, take, with, u, all, th..."
4,5,0,factsguide: society now #motivation,factsguide society now motivation,"[, factsguide, society, now, , , , motivation]","[, factsguid, societi, now, , , , motiv]","[, factsguide, society, now, , , , motivation]"